version: '3'

services:

  julo-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5050:5050"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
      POSTGRES_DB: julo
    volumes:
      - ./db/:/var/lib/postgresql/data/

volumes:
  db: